import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Strepscan Webapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="public/icons/favicon.ico" />
      </Head>

      <div>
        <button id="installApp">Install</button>
      </div>

      <div>
        <div id="liveVideo">
          <video id="webcam" autoplay></video>
          <canvas id="canvas"></canvas>
        </div>

        <p id="information">
          Loading model. Please wait before starting camera.
        </p>
        <div class="video-controls">
          <button id="play" title="Play">
            Start camera
          </button>
          <button id="pause" title="Pause">
            Pause
          </button>
          <button id="save-image" title="Save">
            Save Image
          </button>
          <button id="view" title="View">
            View Photos
          </button>
        </div>
        <div>
          <input type="range" id="zoom" name="zoom">
            <label for="zoom">Zoom</label>

            <input type="range" id="focus" name="focus">
              <label for="focus">Focus</label>

              <button id="current-settings">Get current camera settings</button>
            </div>

            <p id="errorMessage"></p>
          </div>
        </div>
      </div>
    </div>
  );
}
